import { assets } from "@/app/assets/assets";
import { title } from "process";

export const productData = [
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening, Hydrating",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening, Hydrating",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening, Hydrating",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening, Hydrating",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening, Hydrating",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, Hypoallergenic",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, Hypoallergenic",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, Hypoallergenic",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, Hypoallergenic",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, Hypoallergenic",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
];
