import { assets } from "@/app/assets/assets";
import { title } from "process";

export const productData = [
  {
    id: 1,
    title: "Serum JAPAN Cherry Blossom",
    description: "Brightening and hydrating serum with cherry blossom extract.",
    rating: 4.5,
    price: "$49.99",
    Image: assets.SerumJAPANCherry,
  },
  {
    id: 2,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 3,
    title: "Daily UV Defense Mineral Sunscreen",
    description: "Mineral sunscreen for daily UV protection and hydration.",
    rating: 4.5,
    price: "$49.99",
    Image: assets.DailySunscreen,
  },
  {
    id: 4,
    title: "Jeju Cherry Blossom Jelly Cream",
    description: "Lightweight jelly cream for brightening and hydration.",
    rating: 4.5,
    price: "$49.99",
    Image: assets.jejucherrycream,
  },
  {
    id: 5,
    title: "Super Volcanic pore clay mask",
    description: "Deep-cleansing clay mask for minimizing pores.",
    rating: 4.5,
    price: "$49.99",
    Image: assets.poreclaymask,
  },
  {
    id: 6,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 7,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 8,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 9,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
  {
    id: 10,
    title: "Sile Feel Cotton",
    description: "Ultra-soft, hypoallergenic cotton pads for gentle cleansing.",
    rating: 4.5,
    price: "$19.99",
    Image: assets.SileFeelCotton,
  },
];
