import type { Metadata } from "next";
import React from "react";
import { Manrope, Poppins } from "next/font/google";
import "./globals.css";
import { InitTheme } from "@/providers/Theme/InitTheme";
import { Providers } from "@/providers";
import clsx from "clsx";
import LayoutContent from "./LayoutContent";

const poppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const manRopeFont = Manrope({
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beauty Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={clsx(poppinsFont.variable, manRopeFont.variable)}
      lang="en"
      suppressHydrationWarning
    >
      <head>
        <InitTheme />
        <link href="/favicon.ico" rel="icon" sizes="32x32" />
        <link href="/favicon.svg" rel="icon" type="image/svg+xml" />
      </head>
      <body>
        <Providers>
          <div className={clsx(poppinsFont.variable)} />
          <LayoutContent>{children}</LayoutContent>
        </Providers>
      </body>
    </html>
  );
}
